name: MakeRelease

on:
  release:
    types: [created]
  
env:
  BUILD_TYPE: Release

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GP2040-CE
        uses: actions/checkout@v2
        
      - name: Generate Binaries
        uses : ./.github/workflows/cmake.yml
        
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Test Release"
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
      
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
    env:
          GITHUB_TOKEN: ${{ github.token }}
